### ISSUE TITLE
Google Search Appliance Plugin

### ISSUE THREAD

**Issue by ewlarson** [UMNLibraries/janus-uri-factory-plugins#1]
Please add a GSA plugin for me.  Libraries HTML example below:

`<form action="//google.umn.edu/search" class="footer-site-search" method="get" name="footer-site-search">
  <div class="input-group">
    <label class="offscreen" for="footer-site-search">Search the University Libraries website</label>
    <input class="form-control" id="footer-site-search" name="q" placeholder="Search the University Libraries website">
    <input name="client" type="hidden" value="tc_libraries">
    <input name="domains" type="hidden" value="www.lib.umn.edu">
    <input name="proxystylesheet" type="hidden" value="tc_libraries">
    <input name="output" type="hidden" value="xml_no_dtd">
    <input name="site" type="hidden" value="tc_libraries"> <span class="input-group-btn"> <button class="btn" type="submit"> <em class="icon-search"></em> Go </button> </span> 
  </div>
</form>`

Also consider options for GSA form on HSL sites -- using the scope option?  

Site params above "scopes" the GSA index to our library web pages.  
Site params below "scopes" the GSA index to HSL web pages.
Styling is guided by the proxystylesheet param in both cases, too.

HSL example below:
`<form action="//google.umn.edu/search" class="form form-inline pull-right ga-track" method="get" role="search" style="float:right;clear:both;" title="Search Websites and People">
  <div class="input-group">
    <label class="sr-only" for="umnheader-search">Search</label>
    <input class="form-control input-sm" id="umnheader-search" name="q" placeholder="Search HSL" style="border-top-left-radius:4px;border-bottom-left-radius:4px;" type="text">
    <input name="site" type="hidden" value="tc_libraries_hsl">
    <input name="client" type="hidden" value="searchumn_generic">
    <input name="proxystylesheet" type="hidden" value="tc_libraries_hsl">
    <input name="output" type="hidden" value="xml_no_dtd">
    <span class="input-group-btn">
      <button class="btn btn-sm btn-umn-maroon" style="background-color:#47000f; border:1px solid #47000f;" type="submit">
        <i class="icon-search"></i>
        <span class="sr-only">Submit</span>
      </button>
    </span>
  </div>
</form>`

**Comment by ewlarson** [comment]
Any update here?  I'm excited to send you data.

**Comment by nihiliad** [comment]
Yes, lots of progress on this today. One question so far: Do we really not use a "domains" param for HSL?

**Comment by ewlarson** [comment]
Indeed, we do not use a "domains" param for HSL.
