### ISSUE TITLE
New Umedia search format support needed soon

### ISSUE THREAD

**Issue by mberkowski** [UMNLibraries/janus-uri-factory-plugins#17]
The umedia plugin has to be redone to support the new Umedia Archives Rails/Solr application.  The old concept of "collections" we map to scopes now means "contributing organization":

https://lib-umedia-prd-01.oit.umn.edu/facets?browse=true&facet_field=contributing_organization_name_s&facet_limit=400&facet_offset=0&facet_sort=index

Example faceting by contributing org with a `q=` search for "1974 Annual":
`https://lib-umedia-prd-01.oit.umn.edu/search?facets%5Bcontributing_organization_name_s%5D%5B%5D=University+of+Minnesota+Libraries%2C+Charles+Babbage+Institute.&q=1974+Annual`

There is no shortened name for the organization facets. Scopes will need to be defined as the whole string like `University of Minnesota Libraries, Charles Babbage Institute.` as `facets[contributing_organization_name_s][]=University of Minnesota Libraries, Immigration History Research Center Archives.`

The plugin defines fields `titles,creator,subject` but no existing feeder form uses them.

**Comment by mberkowski** [comment]
Question: Do we want/need to support both the old format scopes as `im_og_gid:123456` while we also convert them to look like solr facets?  If we did, we could seamlessly backward-support old janus forms in the wild. But in practice, janus forms drive only a handful of searches into umedia every day. @codyh @nihiliad if you want to weigh in. I would vote for no backward support, and just cut over forms as near to the new umedia's launch as possible.

**Comment by nihiliad** [comment]
I also vote for no backward support, given the very limited use of the UMedia target. Seems like this should be @codyh's decision, though, ultimately.

**Comment by mberkowski** [comment]
Implemented in #19
