### ISSUE TITLE
Primo (mncatdiscovery) integration tests are broken

### ISSUE THREAD

**Issue by mberkowski** [UMNLibraries/janus-uri-factory-plugins#18]
`test/mncatdiscovery.js` has a number of faults when run with `RUN_INTEGRATION_TESTS=true`. DOM matchers all need attention.

**Comment by nihiliad** [comment]
Sorry for neglecting to create an issue for this. I've known about this brokenness ever since a new version of Primo switched to an Angular front end. The current Janus tests don't work with Angular at all.
