### ISSUE TITLE
Primo Formats update and additions

### ISSUE THREAD

**Issue by puzumaki** [UMNLibraries/janus-uri-factory-plugins#33]
We are adding and updating Primo Format plugin options. They are:

Books: &facet=rtype,include,books

Articles: &facet=rtype,include,articles

Journals: &facet=rtype,include,journals

Newspapers (entials passing the query to a different search endpoint): /primo-explore/npsearch?vid=TWINCITIES&search_scope=all&lang=en_US&offset=0&query=any,contains,<QUERY>

Media: &mfacet=rtype,include,images,1&mfacet=rtype,include,videos,1&mfacet=rtype,include,audios,1

Online: &facet=tlevel,include,online_resources$$ITWINCITIES

(Note: the "online" facet will probably change when we move to VE in summer 2023.)

**Comment by mberkowski** [comment]
@puzumaki What's the ideal completion timeline on this?

**Comment by puzumaki** [comment]
By the end of September would be helpful, though it's a "squishy" timeline. The more time we give for QA testing, the better chances we have of releasing it in time for staff to update presentations and roll it out over winter break.
