### ISSUE TITLE
Primo format "realia" to be added

### ISSUE THREAD

**Issue by mberkowski** [UMNLibraries/janus-uri-factory-plugins#45]
A ticket will be coming in to add support for the "realia" format to Primo (main use case will be for a pending Wangensteen update). Seems straightforward, Primo supports it as `facet=rtype,include,realia`  and we might only need to add it to the plugin formats list so it isn't rejected.

Actual specs to follow when available.

**Comment by nihiliad** [comment]
Fixed in 27d1555
